// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "gello_positions_t.h"

static int __gello_positions_t_hash_computed = 0;
static uint64_t __gello_positions_t_hash;

uint64_t __gello_positions_t_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __gello_positions_t_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__gello_positions_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xf9972dadfd98b942LL
         + __int64_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __gello_positions_t_get_hash(void)
{
    if (!__gello_positions_t_hash_computed) {
        __gello_positions_t_hash = (int64_t)__gello_positions_t_hash_recursive(NULL);
        __gello_positions_t_hash_computed = 1;
    }

    return __gello_positions_t_hash;
}

int __gello_positions_t_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const gello_positions_t* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* timestamp */
        thislen = __int64_t_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* joint_positions */
        thislen = __double_encode_array(buf, offset + pos_byte, maxlen - pos_byte, p[element].joint_positions, 6);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* gripper_position */
        thislen = __double_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].gripper_position), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* joint_velocities */
        thislen = __double_encode_array(buf, offset + pos_byte, maxlen - pos_byte, p[element].joint_velocities, 6);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* is_valid */
        thislen = __boolean_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].is_valid), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* arm_side */
        thislen = __string_encode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].arm_side), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int gello_positions_t_encode(void* buf, uint32_t offset, uint32_t maxlen, const gello_positions_t* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __gello_positions_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __gello_positions_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __gello_positions_t_encoded_array_size(const gello_positions_t* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1); // timestamp

        size += __double_encoded_array_size(p[element].joint_positions, 6); // joint_positions

        size += __double_encoded_array_size(&(p[element].gripper_position), 1); // gripper_position

        size += __double_encoded_array_size(p[element].joint_velocities, 6); // joint_velocities

        size += __boolean_encoded_array_size(&(p[element].is_valid), 1); // is_valid

        size += __string_encoded_array_size(&(p[element].arm_side), 1); // arm_side

    }
    return size;
}

uint32_t gello_positions_t_encoded_size(const gello_positions_t* p)
{
    return 8 + __gello_positions_t_encoded_array_size(p, 1);
}

int __gello_positions_t_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, gello_positions_t* p, uint32_t elements)
{
    uint32_t pos_byte = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        /* timestamp */
        thislen = __int64_t_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* joint_positions */
        thislen = __double_decode_array(buf, offset + pos_byte, maxlen - pos_byte, p[element].joint_positions, 6);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* gripper_position */
        thislen = __double_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].gripper_position), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* joint_velocities */
        thislen = __double_decode_array(buf, offset + pos_byte, maxlen - pos_byte, p[element].joint_velocities, 6);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* is_valid */
        thislen = __boolean_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].is_valid), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

        /* arm_side */
        thislen = __string_decode_array(buf, offset + pos_byte, maxlen - pos_byte, &(p[element].arm_side), 1);
        if (thislen < 0) return thislen; else pos_byte += thislen;

    }
    return pos_byte;
}

int __gello_positions_t_decode_array_cleanup(gello_positions_t* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __double_decode_array_cleanup(p[element].joint_positions, 6);

        __double_decode_array_cleanup(&(p[element].gripper_position), 1);

        __double_decode_array_cleanup(p[element].joint_velocities, 6);

        __boolean_decode_array_cleanup(&(p[element].is_valid), 1);

        __string_decode_array_cleanup(&(p[element].arm_side), 1);

    }
    return 0;
}

int gello_positions_t_decode(const void* buf, uint32_t offset, uint32_t maxlen, gello_positions_t* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __gello_positions_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __gello_positions_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int gello_positions_t_decode_cleanup(gello_positions_t* p)
{
    return __gello_positions_t_decode_array_cleanup(p, 1);
}

uint32_t __gello_positions_t_clone_array(const gello_positions_t* p, gello_positions_t* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        n += __double_clone_array(p[element].joint_positions, q[element].joint_positions, 6);

        n += __double_clone_array(&(p[element].gripper_position), &(q[element].gripper_position), 1);

        n += __double_clone_array(p[element].joint_velocities, q[element].joint_velocities, 6);

        n += __boolean_clone_array(&(p[element].is_valid), &(q[element].is_valid), 1);

        n += __string_clone_array(&(p[element].arm_side), &(q[element].arm_side), 1);

    }
    return n;
}

gello_positions_t* gello_positions_t_copy(const gello_positions_t* p)
{
    gello_positions_t* q = (gello_positions_t*) malloc(sizeof(gello_positions_t));
    __gello_positions_t_clone_array(p, q, 1);
    return q;
}

void gello_positions_t_destroy(gello_positions_t* p)
{
    __gello_positions_t_decode_array_cleanup(p, 1);
    free(p);
}

int gello_positions_t_publish(zcm_t* zcm, const char* channel, const gello_positions_t* p)
{
      uint32_t max_data_size = gello_positions_t_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = gello_positions_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _gello_positions_t_subscription_t {
    gello_positions_t_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void gello_positions_t_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    gello_positions_t p;
    memset(&p, 0, sizeof(gello_positions_t));
    status = gello_positions_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding gello_positions_t!!!\n", status);
        #endif
        return;
    }

    gello_positions_t_subscription_t* h = (gello_positions_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    gello_positions_t_decode_cleanup (&p);
}

gello_positions_t_subscription_t* gello_positions_t_subscribe (zcm_t* zcm,
                    const char* channel,
                    gello_positions_t_handler_t f, void* userdata)
{
    gello_positions_t_subscription_t* n = (gello_positions_t_subscription_t*)
                       malloc(sizeof(gello_positions_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              gello_positions_t_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg gello_positions_t ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int gello_positions_t_unsubscribe(zcm_t* zcm, gello_positions_t_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe gello_positions_t_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

